# Generated by Django 2.1 on 2020-07-16 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='科目', max_length=50)),
                ('introduce', models.CharField(db_column='介绍', max_length=100)),
                ('create_time', models.DateField(auto_now_add=True, db_column='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('xz', '选择题'), ('pd', '判断题')], db_column='题型', max_length=10)),
                ('title', models.TextField()),
                ('option_A', models.CharField(db_column='A选项', max_length=100)),
                ('option_B', models.CharField(db_column='B选项', max_length=100)),
                ('option_C', models.CharField(db_column='C选项', max_length=100)),
                ('option_D', models.CharField(db_column='D选项', max_length=100)),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('True', '正确'), ('False', '错误')], db_column='答案', max_length=10)),
                ('score', models.IntegerField(db_column='分值', default=0)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('course_name', models.ForeignKey(db_column='科目', on_delete=django.db.models.deletion.CASCADE, to='exam.Course')),
            ],
        ),
    ]
