# Generated by Django 2.1 on 2020-07-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200716_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_A',
            field=models.CharField(db_column='A选项', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_B',
            field=models.CharField(db_column='B选项', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_C',
            field=models.CharField(db_column='C选项', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_D',
            field=models.CharField(db_column='D选项', max_length=100, null=True),
        ),
    ]
