# Generated by Django 2.1 on 2020-07-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200716_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('true', '正确'), ('false', '错误')], db_column='答案', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_A',
            field=models.CharField(blank=True, db_column='A选项', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_B',
            field=models.CharField(blank=True, db_column='B选项', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_C',
            field=models.CharField(blank=True, db_column='C选项', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_D',
            field=models.CharField(blank=True, db_column='D选项', max_length=100, null=True),
        ),
    ]
