# Generated by Django 2.1 on 2020-07-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20200718_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '科目', 'verbose_name_plural': '科目'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '题库', 'verbose_name_plural': '题库'},
        ),
    ]
