# Generated by Django 2.1 on 2020-07-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mark',
            field=models.IntegerField(db_column='积分', default=0, verbose_name='积分'),
        ),
    ]
