# Generated by Django 2.1 on 2020-07-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mark',
        ),
        migrations.AddField(
            model_name='user',
            name='total_mark',
            field=models.IntegerField(db_column='总积分', default=0, verbose_name='总积分'),
        ),
    ]
